// <auto-generated />
namespace CuaHangDTDD.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class cap_nhat_class_jkasdhjashdjksdasd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cap_nhat_class_jkasdhjashdjksdasd));
        
        string IMigrationMetadata.Id
        {
            get { return "201310221642417_cap_nhat_class_jkasdhjashdjksdasd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
