//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangDTDD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuaHangDTDDEntities : DbContext
    {
        public CuaHangDTDDEntities()
            : base("name=CuaHangDTDDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChiTiet_DonHang> ChiTiet_DonHang { get; set; }
        public DbSet<ChiTiet_NhapHang> ChiTiet_NhapHang { get; set; }
        public DbSet<DonHang> DonHangs { get; set; }
        public DbSet<HangSX> HangSXes { get; set; }
        public DbSet<HinhAnh> HinhAnhs { get; set; }
        public DbSet<MauSac> MauSacs { get; set; }
        public DbSet<NhapHang> NhapHangs { get; set; }
        public DbSet<SanPham_ChiTiet> SanPham_ChiTiet { get; set; }
        public DbSet<SanPham> SanPhams { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<TonKho> TonKhoes { get; set; }
    }
}
